on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches:
      - development
  pull_request:
    types: [opened, synchronize, reopened]
name: Test - SonarCloud Scan
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
      - name: Analyze with SonarCloud
        run: mvn -e -B verify sonar:sonar
          -Dsonar.projectKey=revaturelabs_client-engagement-portal-back
          -Dsonar.organization=revaturelabs-screenforce
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
